version: '3.8'
services:
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./php-app:/var/www/html
    restart: always
    depends_on:
      - php-fpm
      - database
    networks:
      - ecom-network
    
  database:
    build: ./mysql/
    container_name: database
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
    ports:
        - 3306:3306
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    
    networks:
        - ecom-network
  phpmyadmin:
    image: phpmyadmin:latest
    platform: linux/arm64/v8
    container_name: phpmyadmin
    ports:
      - '80:80'
    
    depends_on:
      - database
    environment:
      PMA_PORTS: 3306
      MA_HOST: database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    networks:
      - ecom-network
  php-fpm:
    build: ./php-app/
    container_name: php-fpm
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./php-app:/var/www/html
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge
 